/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tr0nscendence_clipong_Main */

#ifndef _Included_org_tr0nscendence_clipong_Main
#define _Included_org_tr0nscendence_clipong_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tr0nscendence_clipong_Main
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT
void
JNICALL
Java_org_tr0nscendence_clipong_Main_sayHello(
	JNIEnv *env,
	jclass class
	);

#ifdef __cplusplus
}
#endif
#endif
