/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tr0nscendence_clipong_TerminalManager */

#ifndef _Included_org_tr0nscendence_clipong_TerminalManager
#define _Included_org_tr0nscendence_clipong_TerminalManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tr0nscendence_clipong_TerminalManager
 * Method:    isatty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_tr0nscendence_clipong_TerminalManager_isatty
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
